stages:
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - vendor/

build master:
  stage: build
  image: docker:19.03.9-dind
  services:
    - docker:19.03.9-dind
  before_script:
    - alias aws='docker run --rm -i -v ~/.aws:/root/.aws -v $(pwd):/aws amazon/aws-cli'
    - aws --version
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set default.region $AWS_DEFAULT_REGION
  script:
    - export DOCKER_HOST=$DOCKER_PORT
#    - $(aws ecr get-login )
    - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin $REPOSITORY_URL
    - cd website/
    - docker build -t $REPOSITORY_URL:$CI_COMMIT_SHA .
    - docker push $REPOSITORY_URL:$CI_COMMIT_SHA
  only:
    - master
  tags:
    - docker

deploy master:
  stage: deploy
  only:
    - master
  tags: 
    - shell
  before_script:
    - sudo git pull origin master
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set default.region $AWS_DEFAULT_REGION
  script:
    - echo "$SSL_CERT" > nginx/certs/certificate.crt
    - echo "$SSL_PK" > nginx/certs/private.key
    - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin $REPOSITORY_URL
    - export DOCKER_HOST=$DOCKER_PORT
    - sed 's|DOCKERFILE|'"$REPOSITORY_URL":"$CI_COMMIT_SHA"'|g' docker-compose.tpl.yml > docker-compose.yml;
    - docker-compose up -d --build
  environment:
    name: production
    url: https://rifqi.xyz
  
