stages:
  - build
  - deploy


build master:
  stage: build
  image: docker:19.03.9-dind
  services:
    - docker:19.03.9-dind
  before_script:
    - apt install awscli
    - apt-get install python3-pip
    - pip3 install --upgrade awscli
  script:
    - $(aws ecr get-login --no-include-email --region ap-southeast-1)
    - docker build -t $REPOSITORY_URL:CI_COMMIT_SHA
    - docker push $REPOSITORY_URL:$CI_COMMIT_SHA
  only:
    - master
  tags:
    - docker

# deploy master:
#   stage: deploy
#   only:
#     - master
#   tags: 
#     - labrifqi
#   script:
#     - cd /home/ubuntu/Personal-Website
#     - sudo git pull
#   environment:
#     name: dev
#     url: https://rifqi.xyz
  