stages:
  - build
  - test
  - deploy

build:
  stage: build
  tags: 
    - labrifqi
  script:
    - cd /home/ubuntu/Personal-Website
    - sudo git pull
  artifacts:
    paths: 
      - build/
  environment:
    name: dev
    url: https://rifqi.xyz
  

test:
  stage: test
  script:
    - echo "Testing"
    - test -f "build/info.txt" 
  environment:
    name: test
    url: http://lab.rifqi.xyz