stages:
  - build
  - deploy

# cache:
#   key: ${CI_COMMIT_REF_SLUG}
#   paths:
#   - vendor/
  

# build master:
#   stage: build
#   image: docker:19.03.9-dind
#   services:
#     - docker:19.03.9-dind
#   before_script:
# #    - docker run --rm -d amazon/aws-cli:2.0.6
#     - alias aws='docker run --rm -i -v ~/.aws:/root/.aws -v $(pwd):/aws amazon/aws-cli'
#     - aws --version
#   script:
#     - export DOCKER_HOST=$DOCKER_PORT
# #    - $(aws ecr get-login )
#     - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
#     - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
#     - aws configure set default.region $AWS_DEFAULT_REGION
#     - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin $REPOSITORY_URL
#     - docker build -t $REPOSITORY_URL:$CI_COMMIT_SHA ./website
#     - docker push $REPOSITORY_URL:$CI_COMMIT_SHA
#   only:
#     - master
#   tags:
#     - docker

deploy master:
  stage: deploy
  only:
    - master
  tags: 
    - shell
  script:
    - cd /home/ubuntu/Personal-Website
    - sudo git pull
    - echo sed -i -E "s/DOCKERFILE/$REPOSITORY_URL:latest/g" docker-compose.tpl.yml > docker-compose.yml
  #  - sudo docker-compose up --build
  environment:
    name: prod
    url: https://rifqi.xyz
  
