stages:
  - build
  - test
  - deploy


build master:
  stage: build
  script:
    - cd website
    - docker build -t $REPOSITORY_URL:CI_COMMIT_SHA
    - docker push $REPOSITORY_URL:$CI_COMMIT_SHA
  only:
    - master
  tags:
    - labrifqi

# deploy master:
#   stage: deploy
#   only:
#     - master
#   tags: 
#     - labrifqi
#   script:
#     - cd /home/ubuntu/Personal-Website
#     - sudo git pull
#   environment:
#     name: dev
#     url: https://rifqi.xyz
  
