version: "3"
services:
  webserver:
    restart: always
    depends_on: 
      - rifqi-website
    build:  
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports: 
      - 80:80
      - 443:443
    volumes: 
      - ./nginx/certs:/etc/nginx/certs

  rifqi-website:
    restart : always
    build :
      dockerfile: :latest
    volumes: 
      - ./website:/website
    ports:  
      - 8000:8000
